[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["cd backend && npm install"]

[phases.build]
cmds = []

[start]
cmd = "cd backend && npm start"

[env]
NODE_ENV = "production"
PORT = "3000"
API_PREFIX = "/api/v1"
CORS_ORIGIN = "https://diversos-easymarket.yuhqmc.easypanel.host,http://localhost:3001"
JWT_SECRET = "change-me-in-production"
JWT_EXPIRES_IN = "7d"
